services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        ports:
            - "8000:8000"
        container_name: api
        environment:
            # in this test task we provide the address straight,
            # however, in real case, we should walk around with
            # environment variables or secrets
            DB_URL: postgresql+psycopg://postgres:postgres@db_luminary:5432/luminary
        volumes:
            - ./app:/app
        command: uvicorn main:app --host 0.0.0.0 --port 8000

    db_luminary:
        image: postgres:16.10
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: luminary
        ports:
            - "5432:5432"
        container_name: db_luminary
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
