"""add new tables

Revision ID: 226c2112d4d6
Revises:
Create Date: 2026-03-05 14:27:29.785664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "226c2112d4d6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "description", sa.VARCHAR(length=150), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transaction_pkey")),
    )
    op.create_table(
        "transactionentry",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("Debit", "Credit", name="transactiontype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("amount", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("transactionentry_account_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.id"],
            name=op.f("transactionentry_transaction_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transactionentry_pkey")),
    )
    op.create_table(
        "account",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "Asset", "Revenue", "Expenses", "Liability", name="accounttype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("account_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("account_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account")
    op.drop_table("transactionentry")
    op.drop_table("transaction")
    # ### end Alembic commands ###
